### ISSUE TITLE
Authentication help/config/instructions?

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/sails-hook-redbox-storage-mongo#1]
Perhaps this is related to auth.

Our deployment requires authentication, and some cases SSL since it is required by the IT dept and some other cases requires specifying the host.

when sails boot up.

```
AdapterError: Unexpected error from database adapter: not authorized on redbox-storage to execute command { insert: "record", ordered: true, $db: "redbox-storage" }
```

**Comment by shilob** [comment]
Hi Moises,

It looks like it is auth related, so I added a couple of lines in the README regarding the connection options available to you.

Feel free to reach out if this is still an issue.

Thanks!
